jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
    demands: LATEST_DOTNET_VERSION -equals 3.1
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      SonarCloud: true
      SonarCloudProjectKey: SkillsFundingAgency_das-reservations

  - template: azure-pipelines-templates/build/step/dependency-check.yml@das-platform-building-blocks

  - task: DotNetCoreCLI@2
    displayName: 'Publish Website'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.Reservations.Web/SFA.DAS.Reservations.Web.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'
      
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: |
      azure/**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/publish'
